[package]
name = "simple_trie"
version = "0.1.2"
edition = "2021"
description = "A Trie or prefix tree is a specialized tree-like data structure used for efficient storage."
license = "MIT"

[dependencies]
